[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /Users/fperez/teach/berkeley/2017-stat159/stat159
[NotebookApp | INFO] 0 active kernels 
[NotebookApp | INFO] The Jupyter Notebook is running at: http://localhost:8889/?token=0b7d8f4eea7c62019fbca9fdf999943fca03cf11d925903c
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=0b7d8f4eea7c62019fbca9fdf999943fca03cf11d925903c
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from ::1
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | ERROR] Failed to run command:
    ['/usr/local/Cellar/r/3.4.1_2/lib/R/bin/R', '--slave', '-e', 'IRkernel::main()', '--args', '/Users/fperez/Library/Jupyter/runtime/kernel-295f25d6-3639-4164-9d9a-dcb5a1a8da9a.json']
        PATH='/Users/fperez/.local/bin::/Users/fperez/tmp/junk/bin:/Users/fperez/usr/bin:/Users/fperez/usr/local/bin:/Users/fperez/.local/bin:/Users/fperez/usr/conda/bin:/usr/local/bin:/usr/local/texlive/2014/bin/x86_64-darwin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/Users/fperez/teach/berkeley/2017-stat159/stat159', 'start_new_session': True}
    
[NotebookApp | ERROR] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/fperez/.local/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/fperez/.local/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/fperez/.local/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/fperez/.local/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/Users/fperez/usr/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/Users/fperez/.local/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/Users/fperez/.local/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/Users/fperez/.local/lib/python3.6/site-packages/jupyter_client/manager.py", line 257, in start_kernel
        **kw)
      File "/Users/fperez/.local/lib/python3.6/site-packages/jupyter_client/manager.py", line 203, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/Users/fperez/.local/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/Users/fperez/usr/conda/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/Users/fperez/usr/conda/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/r/3.4.1_2/lib/R/bin/R': '/usr/local/Cellar/r/3.4.1_2/lib/R/bin/R'
[NotebookApp | ERROR] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Content-Length": "86",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8889",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|f6ab2f8c|81afc860b68b21d293ef3d3465d287cd|1507708505",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=ir",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "username-localhost-8890=\"2|1:0|10:1507228440|23:username-localhost-8890|44:YjMwZWFiYzJhNzg5NDAzZDhhYjY3NDQ2MzI5NTgyYzU=|9f88f1dcd7abd297e443dd843f4949b36b4633eb29b6a60cbc843dea90ef6c46\"; username-localhost-8891=\"2|1:0|10:1507228739|23:username-localhost-8891|44:ZTVkNjU2ZGIwMmEwNGQxM2E2YzFkMWRhNmU2MDU2OTk=|cda7b2b0a7697f78d22a758077a7d79b1e32937f6fd3cfc1213d260929683bf2\"; username-localhost-8892=\"2|1:0|10:1507244930|23:username-localhost-8892|44:NDZmMWZjNDZhM2M5NGIxMDk1OWExODYxOTZiZmM5ZWE=|60953a48a8f1e313dd6ad6f4d40955a2278366914691c885a8d88d50a71bfafe\"; G_AUTHUSER_H=0; _xsrf=2|f6ab2f8c|81afc860b68b21d293ef3d3465d287cd|1507708505; username-localhost-8888=\"2|1:0|10:1507784763|23:username-localhost-8888|44:MzJmOWIzMGY4NTFiNDU5MGExOGZhZjAzMWY3YTBmZDQ=|74e25f94d1aa69d9c9838692689b53d738bb4c65668a6c8e6244d3d1a1165eec\"; username-localhost-8889=\"2|1:0|10:1507827662|23:username-localhost-8889|44:MzQ2ZGZjN2Q5MWMzNDE4NmFhZGYwM2M0YzNjYjA2Y2I=|0c85234302bc4242ae7de3b39b5b16dde4245f574dc09419405812473a5fac00\""
    }
[NotebookApp | ERROR] 500 POST /api/sessions (::1) 51.34ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=ir
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down kernels
